---

- name: "5.2.2.1 | PATCH | Ensure audit log storage size is configured"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ amzn2023cis_max_log_file_size }}"
  notify: Restart auditd
  when:
      - amzn2023cis_rule_5_2_2_1
  tags:
      - level2-server
      - patch
      - auditd
      - rule_5.2.2.1
      - nist_sp800-53r5_AU-8

- name: "5.2.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ amzn2023cis_auditd['max_log_file_action'] }}"
  notify: Restart auditd
  when:
      - amzn2023cis_rule_5_2_2_2
  tags:
      - level2-server
      - patch
      - auditd
      - rule_5.2.2.2
      - nist_sp800-53r5_AU-8

- name: "5.2.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  notify: Restart auditd
  loop:
      - { regexp: '^admin_space_left_action', line: 'admin_space_left_action = {{ amzn2023cis_auditd.admin_space_left_action }}' }
      - { regexp: '^action_mail_acct', line: 'action_mail_acct = {{ amzn2023cis_auditd.action_mail_acct }}' }
      - { regexp: '^space_left_action', line: 'space_left_action = {{ amzn2023cis_auditd.space_left_action }}' }
  when:
      - amzn2023cis_rule_5_2_2_3
  tags:
      - level2-server
      - patch
      - auditd
      - rule_5.2.2.3
      - nist_sp800-53r5_AU-2
      - nist_sp800-53r5_AU-8
      - nist_sp800-53r5_AU-12
      - nist_sp800-53r5_SI-5

- name: PATCH | Configure other keys for auditd.conf
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^{{ item }}( |=)"
      line: "{{ item }} = {{ amzn2023cis_auditd_extra_conf[item] }}"
  loop: "{{ amzn2023cis_auditd_extra_conf.keys() }}"
  notify: Restart auditd
  when:
      - amzn2023cis_auditd_extra_conf.keys() | length > 0
  tags:
      - level2-server
      - patch
      - auditd
