---

- name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

  vars:
      warn_control_id: '1.1.7.1'
      required_mount: '/home'
  when:
      - required_mount not in mount_names
      - amzn2023cis_rule_1_1_7_1
  tags:
      - level2-server
      - audit
      - mounts
      - rule_1.1.7.1
      - nist_sp800-53r5_CM-6

- name: |
    "1.1.7.2 | PATCH | Ensure nodev option set on /home partition
     1.1.7.3 | PATCH | Ensure nosuid option set on /home partition"
  ansible.posix.mount:
      name: /home
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if amzn2023cis_rule_1_1_7_2 %}nodev,{% endif %}{% if amzn2023cis_rule_1_1_7_3 %}nosuid,{% endif %}
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  notify: Change_requires_reboot
  when:
      - item.mount == "/home"
      - amzn2023cis_rule_1_1_7_2 or
        amzn2023cis_rule_1_1_7_3
  tags:
      - level1-server
      - patch
      - mounts
      - rule_1.1.7.2
      - rule_1.1.7.3
      - nist_sp800-53r5_AC-3
      - nist_sp800-53r5_MP-2
