---

- name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  block:
      - name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
        ansible.builtin.set_fact:
            amzn2023cis_sysctl_update: true

      - name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
        ansible.builtin.debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/60-kernel_sysctl.conf"
  when:
      - amzn2023cis_rule_1_5_1
  tags:
      - level1-server
      - patch
      - sysctl
      - rule_1.5.1
      - nist_sp800-53r5_CM-6

- name: "1.5.2 | PATCH | Ensure ptrace_scope is restricted"
  block:
      - name: "1.5.2 | PATCH | Ensure ptrace_scope is restricted"
        ansible.builtin.set_fact:
            amzn2023cis_sysctl_update: true

      - name: "1.5.2 | PATCH | Ensure ptrace_scope is restricted"
        ansible.builtin.debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/60-kernel_sysctl.conf"
  when:
      - amzn2023cis_rule_1_5_2
  tags:
      - level1-server
      - patch
      - sysctl
      - rule_1.5.2
      - nist_sp800-53r5_CM-6

- name: "1.5.3 | PATCH | Ensure core dump storage is disabled"
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: '^Storage\s*=\s*(?!none).*'
      line: 'Storage=none'
  notify: Systemd daemon reload
  when:
      - amzn2023cis_rule_1_5_3
      - systemd_coredump.stat.exists
  tags:
      - level1-server
      - patch
      - rule_1.5.3
      - nist_sp800-53r5_CM-7

- name: "1.5.4 | PATCH | Ensure core dump backtraces are disabled"
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: '^ProcessSizeMax\s*=\s*.*[1-9]$'
      line: 'ProcessSizeMax=0'
  when:
      - amzn2023cis_rule_1_5_4
  tags:
      - level1-server
      - patch
      - sysctl
      - rule_1.5.4
      - nist_sp800-53r5_CM-6
