---

- name: "1.1.2.1 | PATCH | Ensure /tmp is a separate partition"
  block:
      - name: "1.1.2.1 | PATCH | Ensure /tmp is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.2.1 | PATCH | Ensure /tmp is a separate partition | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.2.1'
      required_mount: '/tmp'
  when:
      - required_mount not in mount_names
      - amzn2023cis_rule_1_1_2_1
  tags:
      - level1-server
      - audit
      - mounts
      - rule_1.1.2.1
      - nist_sp800-53r5_CM-7

# via fstab
- name: |
        "1.1.2.2 | PATCH | Ensure nodev option set on /tmp partition"
        "1.1.2.3 | PATCH | Ensure noexec option set on /tmp partition"
        "1.1.2.4 | PATCH | Ensure nosuid option set on /tmp partition"
  ansible.posix.mount:
      name: /tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if amzn2023cis_rule_1_1_2_2 %}nodev,{% endif %}{% if amzn2023cis_rule_1_1_2_3 %}noexec,{% endif %}{% if amzn2023cis_rule_1_1_2_4 %}nosuid{% endif %}
  notify: Remount tmp
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/tmp"
      - not amzn2023cis_tmp_svc
      - amzn2023cis_rule_1_1_2_2 or
        amzn2023cis_rule_1_1_2_3 or
        amzn2023cis_rule_1_1_2_4
  tags:
      - level1-server
      - patch
      - mounts
      - rule_1.1.2.2
      - rule_1.1.2.3
      - rule_1.1.2.4
      - nist_sp800-53r5_CM-7

# via systemd
- name: |
        "1.1.2.2 | PATCH | Ensure nodev option set on /tmp partition"
        "1.1.2.3 | PATCH | Ensure noexec option set on /tmp partition"
        "1.1.2.4 | PATCH | Ensure nosuid option set on /tmp partition"
  ansible.builtin.template:
      src: etc/systemd/system/tmp.mount.j2
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: '0644'
  notify: Systemd restart tmp.mount
  when:
      - amzn2023cis_tmp_svc
      - amzn2023cis_rule_1_1_2_2 or
        amzn2023cis_rule_1_1_2_3 or
        amzn2023cis_rule_1_1_2_4
  tags:
      - level1-server
      - patch
      - mounts
      - rule_1.1.2.2
      - rule_1.1.2.3
      - rule_1.1.2.4
      - nist_sp800-53r5_CM-7
      - nist_sp800-53r5_AC-3
      - nist_sp800-53r5_MP-2
